# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3464e02e49847d4bd18ec449071fc88c7ac14db47c7a8787fe15bf415e2a0720be66a73c1ead3299634f962baef7bd2cb10e27b2b3aa60dae5f570b37cad0ea

test:
  secret_key_base: 35a0d59df48f8eb4bfbf73d423f55c3e52e94677923fb9f2ac8b4e9307931b54e614d918585c5237f63e963cf8f537d23745eb03277527f26e7b271b91656913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
